version: '4'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-inventory-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql